### ISSUE TITLE
Map current ATO Process: Convert notes to digital

### ISSUE THREAD

**Issue by its-a-lisa** [18F/Security-Compliance#6]
## Background

Met with folks in the #c-compliance-security guild and took [notes](https://gsa-tts.slack.com/archives/CG8SNAEQM/p1581110946079700?thread_ts=1581092101.070200&cid=CG8SNAEQM) on a whiteboard

https://github.com/18F/tts-tech-portfolio/issues/344

https://github.com/18F/Security-Compliance/issues/2

## Acceptance Criteria

- [ ] Convert notes from pictures to digital format

**Comment by rahearn** [comment]
@its-a-lisa There's a mural started (barely) for this as well. We should combine forces

**Comment by its-a-lisa** [comment]
Closing based on the decision made on 4/21/20 to close anything that wasn't a Major current Initiative or Notable mention from the [Tech Portfolio Sprint Planning 2020-04-20](https://docs.google.com/document/d/1Q4XRL47tCva3PrIBa5WVcPAtYwv8nFgnyNH6RelnsFc/edit) radiated intent in [slack](https://gsa-tts.slack.com/archives/CNW3GL70S/p1587578121241100) and open for discussion on reopening.
